version: '3'
services:
  azure-vote-back:
    image: redis
    container_name: azure-vote-back
    ports:
        - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: azure-vote-front
    container_name: azure-vote-front
    environment:
      REDIS: azure-vote-back
    ports:
        - "1338:80"

  azure-calculator-api:
    build: ./calculator-api
    image: azure-calculator-api
    container_name: azure-calculator-api
    ports:
        - "1339:8080"